### ISSUE TITLE
Space above bottom navigation bar

### ISSUE THREAD

**Issue by JordanGout** [thrive-now/BottomNavigationBarXF#6]
I always have a space between the BottomNavigationBar and the ContentPage. 

With a Pixel C (Android 7) the space is small (see screen 1) but with an old little samsung tablet the space is important... (see screen 2)

Screen 1:
![android 7](https://cloud.githubusercontent.com/assets/5838406/17246774/89f41122-558e-11e6-905e-1e224445c6f9.png)

Screen 2:
![android 4 2 2](https://cloud.githubusercontent.com/assets/5838406/17246773/89f26a66-558e-11e6-83f2-a8d9da266696.png)

**Comment by andreinitescu** [comment]
I think the issue comes from this line

https://github.com/thrive-now/BottomNavigationBarXF/blob/master/BottomBar.Droid/Renderers/BottomBarPageRenderer.cs#L187

That line computes the area where the child pages are put.

**Comment by Korayem** [comment]
Changing that line mentioned by @andreinitescu to the following fixes my problem:
`_pageController.ContainerArea = new Rectangle(0, 0, context.FromPixels(width), context.FromPixels(height - 115));`

**Comment by ice-j** [comment]
So basically, changing it to another magic number won't fix the bug. You got it fixed because your device's display is HD, so the number is 115, on FHD is 168, and the generic solution to this problem is the following:

```
int ninePercentsOfHeight = (int)Math.Ceiling((height * 0.909));
				_pageController.ContainerArea = new Rectangle(0, 0, context.FromPixels(width), context.FromPixels(ninePercentsOfHeight));
```

With "nine" percents of the height, well not exactly 9 but the value above, you get the correct container area on any device (tested with QHD, HD, FHD). Should I do a PR with this?

**Comment by JordanGout** [comment]
@ice-j I will try your fix but à PR would be great

**Comment by sschmidt** [comment]
Merged the PR - thanks guys! Can you verify that it's working in master? Looks good to me. I'll publish a new nuget version once we have that verified.

**Comment by DominicFrei** [comment]
@JordanGout @sschmidt @andreinitescu @Korayem @ice-j Are we done here? Does it work to your satisfaction so that I can close this issue?

**Comment by Korayem** [comment]
Ok

**Comment by DominicFrei** [comment]
Going to close this for now. If something re-arises, feel free to reopen this issue with new information.

**Comment by ice-j** [comment]
Looks like it was not fully working, and I as a developer didn't like that magic number calculation, so I think that now will be working better, and can say that this bug is fixed with #21

**Comment by jbucka** [comment]
@ice-j @DominicFrei The problem has not dissappeared entirely. I still get the extra bar when first launching the app in the simulator, as well as when changing between landscape and portrait mode.

Once I then click on another tab, the bar dissappears, until I either reopen the app or change between landscape and portrait.

**Comment by ice-j** [comment]
@jbucka I think that there's no new nuget yet with my changes. Are you using the nuget package or you built one yourself one locally?

**Comment by jbucka** [comment]
@ice-j I built  the project myself locally after your push request was accepted.

**Comment by jbucka** [comment]
@dominicfrei can we please reopen this? Issue isnt fully fixed. I have tried to play around with the source but not managed to get to the bottom of it. Can someone else confirm that they can reproduce the issue?

**Comment by DominicFrei** [comment]
@jbucka Can you provide an example project or something like this so that the others can understand the problem?

**Comment by jbucka** [comment]
@DominicFrei @ice-j Apologies for the delay, sample code is at:

https://github.com/jbucka/App1

**Comment by hardcodet** [comment]
Possibly related:

* Start the sample in portrait mode.
* Turn phone to landscape mode.
* Switch back to portrait mode - layout is not probably refreshed.

**Comment by ice-j** [comment]
We should add Rotation listener to properly handle layout after rotation. I'm sorry but I'm very busy this week, I'll do it during the weekend if somebody else can't find the time before that.

**Comment by jbucka** [comment]
@ice-j Thanks for your help, I will happily wait for the weekend, if you can make it work. 

I managed to add an eventHandler to the BottomBarPage and react to that eventHandler in the Renderer, but then I am at a total loss what I would need to do to reset the layout. Basically I am messing with code I don't fully understand, so not getting anywhere.

I look forward to seeing your solution.

**Comment by lengluo** [comment]
I have the same issue, when reload the bar, a space will appear above. But when I select the tab, it will disappear. Wait for a solution.

**Comment by jbucka** [comment]
@ice-j Do you think you might be able to take a look at this soon? Otherwise any hints how I would rerender everything once the rotation event triggers.

**Comment by lengluo** [comment]
aha, I solved this problem by commenting this line
`_pageController.ContainerArea = new Rectangle(0, 0, context.FromPixels(width), context.FromPixels(_frameLayout.Height));`
in the function "OnLayout" in the Renderer. But I don't know what this code means, and why it works in this way.

**Comment by ice-j** [comment]
I can't right now. But my try would be to implement `ISensorListener` which then let's you override 2 methods, `OnAccuracyChanged` and `OnSensorChanged` which looks like this:
```
public void OnAccuracyChanged([GeneratedEnum] SensorType sensor, [GeneratedEnum] SensorStatus accuracy)
        {
            throw new NotImplementedException();
        }

        public void OnSensorChanged([GeneratedEnum] SensorType sensor, float[] values)
        {
            if(sensor == SensorType.Orientation)
            {

            }
        }
```

And in the if block, measure the views again or redraw them, I'd first try to call _bottomBar.SelectTabAtPosition() in there, or SwitchContent()

It'd be awesome if you could try this and come back here with results.

**Comment by gcadmes** [comment]
ice-j,

Some good news...I was able to get it working, but not with the ISensorListener.
The ISensorListener didn't work, prob because of being deprecated. Also couldn't get the ISensorEventListener working.

Instead, I override the OnSizeChanged and detected the orientation changes that way (w > h). When the orientation changes to vertical, I invoke the  _bottomBar.SelectTabAtPosition(), which then re-draws the UI correctly. 

I would have rather implemented a well-known interface for detecting orientation changes, but decided to use the Xamarin hack instead.

**Comment by lengluo** [comment]
@gcadmes I don't think it's just occurred in orientation change, you'll get this issue if click the backbutton of NavigationPage,  another way of saying,  just return from NavigationPage, the empty space will happens again.

**Comment by ice-j** [comment]
@gcadmes thank you, it'd be awesome if you could do a PR, if not I'll do it this weekend. 
@lengluo I'm using a navigation page currently, and have no problem as yours, can you please do a sample  that reproduces your problem?

**Comment by lengluo** [comment]
@ice-j Thank you for your time, It maybe a special case in my app context. I have found a  way seams dirty but works to resovle it.
Put a static variable named "_frameLayoutHeiht" in renderers, then do it in the OnLayout event like blow
`if (_frameLayout.Height >= 0 && _frameLayoutHeiht == 0)
                {
                    _frameLayoutHeiht = _frameLayout.Height;
                }
                var currHeight = _frameLayoutHeiht;
                if (_frameLayoutHeiht != _frameLayout.Height && _frameLayoutHeiht  < _frameLayout.Height + 100) currHeight = _frameLayoutHeiht + 50;
                _pageController.ContainerArea = new Rectangle(0, 0, context.FromPixels(width), context.FromPixels(currHeight));`
It works fine in three different devices with different resolution each other. Although it's dirty but sufficient for me, but i'd like to wait for a elegant way.

**Comment by lengluo** [comment]
@ice-j Thank you for your reply. I don't know why it happens in my case.  And I have resolved this issue by a dirty way:
  `if (_frameLayout.Height >= 0 && _frameLayoutHeiht == 0)
{
    _frameLayoutHeiht = _frameLayout.Height;
}
var currHeight = _frameLayoutHeiht;
if (_frameLayoutHeiht != _frameLayout.Height && _frameLayoutHeiht  < _frameLayout.Height + 100) 
  currHeight = _frameLayoutHeiht + 50;
_pageController.ContainerArea = new Rectangle(0, 0, context.FromPixels(width), context.FromPixels(currHeight));`
and it seems work fine in my phones with different resolution as well as in genymotion. And I still want to know the reason why this happens.

**Comment by Tany3450** [comment]
Still not available on nuget?

**Comment by ice-j** [comment]
@Ironthighs I've not tested that scenario with a carousel page, it would be great if you could publish the test project so  I can look into it.

**Comment by Ironthighs** [comment]
@ice-j The project as it is now has this space on the first page. Tap a new tab and it's gone. I just created a pull request fixing this issue. Please have a look.
